# ===============================================================
#                             Taps
# ===============================================================

tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/core'
tap 'pivotal/tap'
tap 'cloudfoundry/tap'

# ===============================================================
#                           Binaries
# ===============================================================

brew 'coreutils'
brew 'nvim'
brew 'wget'
brew 'git-together'
brew 'node'
brew 'yarn'
brew 'yarn-completion'
brew 'mysql'
brew 'zsh-completion'
brew 'diff-so-fancy'
brew 'cf-cli'


# ===============================================================
#                           MacOS Apps
# ===============================================================

cask 'chromium'
cask 'firefox'
cask 'iterm2'
cask 'vscodium'
cask 'intellij-idea'
cask 'slack'
cask 'hammerspoon'
cask 'rar'
cask 'kitty'

# ===============================================================
#                           MacOS Fonts
# ===============================================================

cask 'font-hasklig-nerd-font'
cask 'font-hasklig-nerd-font-mono'
cask 'font-fira-code'
cask 'font-victor-mono'
